name: Schedule Event
on:
    workflow_dispatch:
        
    schedule:
      - 
        cron: '30 22 * * 6'
jobs:
  Schedule:
    runs-on: ubuntu-latest
    steps:
        - 
            name: clone
            uses: actions/checkout@v3
        -
            name: run script
            run: bash src/main.sh